let g:vimsence_client_id = '439476230543245312'
let g:vimsence_small_text = 'Neovim'
let g:vimsence_small_image = 'neovim'
let g:vimsence_editing_details = 'Editing: {}'
" let g:vimsence_editing_state = 'Working on: {}'
let g:vimsence_file_explorer_text = 'CoC Explorer'
let g:vimsence_file_explorer_details = 'File Explorer'
